# Generated by Django 4.2.3 on 2023-07-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('phone_number', models.CharField(default='+375', max_length=13, verbose_name='Номер телефона')),
                ('type_of_learning', models.BooleanField(default=True, verbose_name='Тип занятия(галочка если оффлайн)')),
                ('physics_learn', models.BooleanField(default=False, verbose_name='Занятия по физике')),
                ('math_learn', models.BooleanField(default=False, verbose_name='Занятие по математике')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
