# Generated by Django 4.2.3 on 2023-07-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queries1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(default='+375', max_length=13, verbose_name='Номер телефона')),
                ('type_of_learning', models.BooleanField(default=False, verbose_name='Онлайн обучение')),
                ('physics_learn', models.BooleanField(default=False, verbose_name='Занятия по физике')),
                ('math_learn', models.BooleanField(default=False, verbose_name='Занятие по математике')),
            ],
            options={
                'verbose_name': 'Заявка (ЦТ/ЦЭ)',
                'verbose_name_plural': 'Заявки (ЦТ/ЦЭ)',
            },
        ),
        migrations.CreateModel(
            name='Queries2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(default='+375', max_length=13, verbose_name='Номер телефона')),
                ('type_of_learning', models.BooleanField(default=False, verbose_name='Онлайн обучение')),
                ('math_learn', models.BooleanField(default=False, verbose_name='Занятие по математике')),
            ],
            options={
                'verbose_name': 'Заявка (После 9-го)',
                'verbose_name_plural': 'Заявки (После 9-го)',
            },
        ),
    ]
